### ISSUE TITLE
Inquiry About Code Release for ECCV 2024

### ISSUE THREAD

**Issue by hechengbo-H** [zhengzhang37/LECODU#1]
hi， I noticed your mention of releasing the code on GitHub after ECCV 2024. Based on what you previously mentioned, I wanted to ask if you still plan to make the code available.

**Comment by zhengzhang37** [comment]
Yes, I plan to update the code in next two weeks.

**Comment by hechengbo-H** [comment]
I encountered an issue with missing files while debugging and running the code. The following files are mentioned in the code:

../cifar10nh_checkpoints/cifar10_random_label1_best.pth.tar

../cifar-10h/cifar-10-batches-py

../cifar-10h/CIFAR-10_human.pt

../data/cifar-10h/cifar-10-npy/test_images.npy

However, I could not find these files in the source directory. Could you please let me know where I can obtain them? Are there any relevant download links or resources where I can get these files?

I would appreciate any guidance or assistance in this matter.

Thank you for your help!
